{
 "title": "Geekshop dashboard",
 "time": { "from": "now-5d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(nginx_up,instance)"
    }
   },
   {
    "name": "nodeExporterInstance",
    "query": {
     "query": "label_values(node_exporter_build_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nginx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Nginx logs by status",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "count by(status) (rate({container_name=\"nginx_container\", status!=\"\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Nginx logs by method",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "count by(method) (rate({container_name=\"nginx_container\", status!=\"\"} [$__interval]))"
    },
    {}
   ]
  },
  {
   "title": "System nginx log",
   "type": "logs",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{container_name=\"nginx_container\", status=\"\"}"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"$nodeExporterInstance\", mountpoint=~\"/(data)?\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Total space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$nodeExporterInstance\", mountpoint=~\"/(data)?\",fstype!=\"rootfs\"}"
    }
   ]
  }
 ]
}