version: '3.1'

services:
  django_server:
    container_name: 'backend_django_now'
    build:
      context: ..
    image: backend_django:1.0.0
    ports:
      - 80:80
    command: > 
      bash -c "python manage.py migrate
      && python manage.py fill_db 
      && python manage.py runserver 0.0.0.0:80"
