version: '3.7'

services:
  db:
    image: postgres:13.1
    container_name: postgres_container
    privileged: true
    expose:
      - 5432
    environment:
      POSTGRES_USER: geekbrains
      POSTGRES_PASSWORD: geekbrains
      POSTGRES_DB: geekshop

  db_check:
    image: db_check
    container_name: db_check_container
    build: ./db_check
    depends_on:
      - db


  adminer:
    image: adminer:4.7.8-standalone
    container_name: adminer_container
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
      - db_check

  django_server:
    image: django:1.0.0
    container_name: django_container
    build:
      context: ..
    expose:
      - 8000
    volumes:
      - media_volume:/media
      - static_volume:/static
    environment:
      - GEEKSHOP_ON_SERVER=True
    command: >
      bash -c "python manage.py migrate
      && python manage.py collectstatic --noinput
      && python manage.py fill_db 
      && gunicorn geekshop.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
      - db_check
      - adminer

  nginx:
    image: nginx
    container_name: nginx_container
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - media_volume:/media
      - static_volume:/static
    depends_on:
      - db
      - db_check
      - adminer
      - django_server

volumes:
  media_volume:
  static_volume:
