# Generated by Django 3.2.9 on 2021-11-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_shopuser_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuser',
            old_name='avatar',
            new_name='image',
        ),
    ]
