# Generated by Django 4.0.4 on 2022-04-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_shopuser_activation_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopuser',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='shopuser',
            unique_together={('email',)},
        ),
    ]
