{
 "title": "Main dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Nginx logs by status panel",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by(status) (rate({container_name=\"nginx_container\", status!=\"\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Nginx logs by method panel",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count by(method) (rate({container_name=\"nginx_container\", status!=\"\"} [$__interval]))"
    },
    {}
   ]
  },
  {
   "title": "System nginx log Panel",
   "type": "logs",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container_name=\"nginx_container\", status=\"\"}"
    }
   ]
  }
 ]
}