global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']
  - job_name: 'node_stats'
    static_configs:
      - targets: ['node-exporter:9100']
